name: Dev2 generate Swagger UI and publish to GitHub Pages
on:
  push:
    branches:
      - dev2
jobs:
  # upload-openapi-spec:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Upload openapi.json
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: spec-file
  #         path: openapi.json
  
  deploy-swagger-ui:
    # needs: upload-openapi-spec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          token: ${{ secrets.ACCESS_TOKEN }}
      # - name: Download openapi.json
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: spec-file
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: ./resources/openapi.json
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui