name: Dev2 generate Swagger UI and publish to GitHub Pages
on:
  push:
    branches:
      - dev2

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Generate Swagger UI 
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: ./resources/openapi.json
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire UI
          path: ./swagger-ui
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui

# https://steve-pedersen.github.io/test-swagger-actions